#!/usr/bin/env python

# Fontconvert is (c) 2012 Manufactura Independente (Ana Carvalho & Ricardo
# Lafuente) Licensed under the GPL v3 or later version.

# modified to remove overlap and simplify font by pippin@gimp.org 2013-05-21

import sys, os
import fontforge
import psMat
import math
import optparse

# print 'ARGV      :', sys.argv[1:]
parser = optparse.OptionParser()
parser.add_option('-w', '--woff', 
                  dest="woff", 
                  action="store_true",
                  default=False,
                  help='Save in WOFF format (.woff)'
                  )
parser.add_option('-o', '--otf', 
                  dest="otf", 
                  action="store_true",
                  default=False,
                  help='Save in OpenType format (.otf)'
                  )
parser.add_option('-t', '--ttf', 
                  dest="ttf", 
                  action="store_true",
                  default=False,
                  help='Save in TrueType format (.ttf)'
                  )
parser.add_option('-s', '--svg', 
                  dest="svg", 
                  action="store_true",
                  default=False,
                  help='Save in SVG Font format (.svg)'
                  )
parser.add_option('-e', '--eot', 
                  dest="eot", 
                  action="store_true",
                  default=False,
                  help='Save in Embedded OpenType format (.eot)'
                  )
parser.add_option('-u', '--ufo', 
                  dest="ufo", 
                  action="store_true",
                  default=False,
                  help='Save in UFO format (.ufo)'
                  )
options, remainder = parser.parse_args()

if not len(remainder) == 1:
    print "Only one non-keyword argument allowed."
    sys.exit()

fontname = remainder[0]
font = fontforge.open(fontname)

d = os.path.dirname(os.path.abspath(fontname)) + '/'
filename = os.path.basename(fontname)
basename, ext = os.path.splitext(filename)

font.selection.all();
font.removeOverlap();
# this makes the font oblique;- which is what we want..
#font.transform(psMat.skew(0.2))
font.selection.all();
font.simplify();


font.selection.all();
font.addExtrema();
font.selection.all();
font.simplify();
font.selection.all();

font.selection.all();
font.autoHint();


print d
print filename
print basename

woff_filename = d + basename + '.woff'
otf_filename = d + basename + '.otf'
ttf_filename = d + basename + '.ttf'
svg_filename = d + basename + '.svg'
eot_filename = d + basename + '.eot'
ufo_filename = d + basename + '.ufo'


if options.woff:
    print woff_filename
    font.generate(woff_filename)
if options.otf:
    print otf_filename
    font.generate(otf_filename)
if options.ttf:
    print ttf_filename
    font.generate(ttf_filename)
if options.svg:
    print svg_filename
    font.generate(svg_filename)
if options.ufo:
    print ufo_filename
    font.generate(ufo_filename)
if options.eot:
    print eot_filename
    if options.ttf:
        cmd = 'ttf2eot < %s > %s' % (ttf_filename, eot_filename)
        os.system(cmd)
    else:
        font.generate(ttf_filename)
        cmd = 'ttf2eot < %s > %s' % (ttf_filename, eot_filename)
        os.system(cmd)
        os.remove(ttf_filename)
